version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - /doesnotexist
    schedule:
      interval: "daily"
    groups:
      all-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
