version: 2
updates:
  - package-ecosystem: "npm"
    allow:
      - dependency-name: "js-yaml"
    directories:
      - /
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "handlebars"
        update-types: ["< 0.x"]
