version: 2
updates:
  - package-ecosystem: npm
    allow:
      - dependency-name: "js-yaml"
    directories:
      - /
    schedule:
      interval: "daily"
    groups:
      all-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
