version: 2
updates:
  # - package-ecosystem: npm
  #   allow:
  #     - dependency-name: "js-yaml"
  #   directories:
  #     - /
  #   schedule:
  #     interval: "daily"
  #   groups:
  #     all-deps:
  #       patterns:
  #         - "js-yaml"
  #       update-types:
  #         - "minor"
  #         - "patch"

  - package-ecosystem: pip
    directories:
      - /PEP-621
      - /setup-py
    schedule:
      interval: "daily"

  - package-ecosystem: uv
    directories:
      - uv
      - uv-PEP-751
    schedule:
      interval: "daily"

  - package-ecosystem: uv
    directories:
      - /PEP-621
    dependency-type: "direct"
    schedule:
      interval: "daily"      
