[project]
name = "tester"
version = "0.0.1"
description = "Test project"
requires-python = ">=3.10"
dependencies = [
    "requests==2.28.1"
]

[project.optional-dependencies]
dev = [
    "pytest==8.4.1"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"